### ISSUE TITLE
️🛠 - Enable amplitude analytics for all routes

### ISSUE THREAD

**Issue by Tuditi** [bloomwalletio/bloom#1111]
### Task description

Ensure that analytics for the different routes are working.

### Requirements

- [x] Add tracking for all routers (@maxwellmattryan)
- [ ] Cleanup Amplitude dashboard (@nicole-obrien)
    - [ ] Setup different projects per app stage
