### ISSUE TITLE
️🛠 - Update activity details popup

### ISSUE THREAD

**Issue by MarkNerdi** [bloomwalletio/bloom#1162]
### Task description

- [x] Move timelock/expiration/claim pill into table
- [x] fix explorer link container
- [x] remove old pills
- [x] dont use glow, only show shimmer amounts
- [ ]
