### ISSUE TITLE
️🛠 - Update production icons on all platforms

### ISSUE THREAD

**Issue by jeeanribeiro** [bloomwalletio/bloom#1361]
### Task description

Now we have a prod icon for all platforms in Figma, so we need to update it in our repo

### Requirements

- [ ] Windows has updated prod icon
- [ ] Linux has updated prod icon
- [x] MacOS has updated prod icon
