### ISSUE TITLE
️🛠 - [Task tracker]: Dark mode

### ISSUE THREAD

**Issue by jeeanribeiro** [bloomwalletio/bloom#1411]
### Task description

We need to polish dark mode so it can be released to users

### Requirements

- [x] bloomwalletio/bloom-ui#207
- [x] bloomwalletio/bloom-ui#255
- [x] bloomwalletio/bloom-ui#257
- [x] #1445
- [x] #1439
- [x] #1442
- [x] #1441
- [x] Fix darkmode on MnemonicInput
- [x] #1444
- [x] #1446
- [ ] #1447
