### ISSUE TITLE
️🛠 - Add support for automatically tracking ERC721 NFTs

### ISSUE THREAD

**Issue by maxwellmattryan** [bloomwalletio/bloom#1449]
### Task description

Users should have their NFTs automatically populate within their own wallets.

### Requirements

- [x] Modify existing `persistedNfts` store and interfaces
- [x] Add token URI to metadata (for each instance) - think if data for instance wasn't downloaded, the URI needs to be stored
- [ ] Error handling 
- [ ] Migration functions
- [ ] More function cleanup
