### ISSUE TITLE
️🛠 - Mint NFT collection

### ISSUE THREAD

**Issue by nicole-obrien** [bloomwalletio/bloom#1516]
### Task description

We need the ability to mint simple nft collections

### Requirements

- [x] Mint collection as AliasOutput
- [x] Mint NFT with Alias as issuer
- [ ] Add alias based irc27 nfts to collectibles tab
- [x] Add activity for minting alias nft collection
- [ ] Refactor to have flow rather than individual popups
