### ISSUE TITLE
️🛠 -  Add `AddEvmChainForm` validation logic

### ISSUE THREAD

**Issue by Tuditi** [bloomwalletio/bloom#153]
### Task description

With the form to add an EVM chain stubbed out, the next step is adding form validation logic.

Blocked by https://github.com/bloomwalletio/bloom/issues/152

### Requirements

- [ ] Add AddEvmChainForm component to AddChainDrawer (no validation logic)

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
