### ISSUE TITLE
️🛠 - Polish Wallet Connect

### ISSUE THREAD

**Issue by Tuditi** [bloomwalletio/bloom#1561]
### Task description

The final polish for wallet connect includes the following things:

- [x] Square checkbox in [ConnectionRequestDrawer l.129](https://github.com/bloomwalletio/bloom/blob/6185639c87cfef36451917b9c2c57da67992bb70/packages/desktop/views/dashboard/drawers/dapp-config/views/ConnectionRequestDrawer.svelte)
- [x] Max height for `PopupTemplate`
- [x] Smaller data field for smart contract transactions & make the copyable
- [x] Handle opening settings while the send transaction pop-up is open.
- [x] Decrease inner padding if popup banner is set
