### ISSUE TITLE
️🛠 - Add menu button to Asset list

### ISSUE THREAD

**Issue by MarkNerdi** [bloomwalletio/bloom#174]
### Task description

Add a menu button to the assetlist on the top right. This button should include the "Import ERC20"

### Requirements

- [ ] Add Menu button to asset list
- [ ] Move "Import ERC20" button to menu

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
