### ISSUE TITLE
️🛠 - Improve activity row

### ISSUE THREAD

**Issue by MarkNerdi** [bloomwalletio/bloom#1893]
### Task description

- [ ] Update action colors
- [x] show dash on Nfts
- [x] instead of NFT name, show "1 NFT"
- [x] show fee in fiat
- [x] show less decimals on fee
