### ISSUE TITLE
️🛠 - Remove old send flow

### ISSUE THREAD

**Issue by Tuditi** [bloomwalletio/bloom#198]
### Task description

With the new send flow in place, it's time to remove the old send form.

### Requirements

- [x] Deep links are working with the dev tools tester
- [x] Feature flag removed
- [x] New send flow working for coin, native token & NFTs
