### ISSUE TITLE
️🛠 - Polish Governance

### ISSUE THREAD

**Issue by Tuditi** [bloomwalletio/bloom#2007]
### Task description

- [x] Define voteStarted/voteStarting locale
![image](https://github.com/bloomwalletio/bloom/assets/45079109/a66a32ba-8800-4b7b-bee6-59cb7727270d)
- [x] Fix total votes counted
- [x] Background hover effect:
![image](https://github.com/bloomwalletio/bloom/assets/45079109/7f6edb95-5903-46b0-a496-47f46a326858)
- [x] Color of error state (e.g. removed node)

### Requirements

TBD
