### ISSUE TITLE
️🛠 - Refactor `network-config` drawers

### ISSUE THREAD

**Issue by maxwellmattryan** [bloomwalletio/bloom#224]
### Task description

There are a few things wrong with this area in the code.

### Requirements

- [ ] Rename drawer router component `NetworkConfigRouterView`
- [ ] Move `network-config` drawer folder to `desktop/views` 
- [ ] Move the router files alongside the components
