### ISSUE TITLE
️🛠 - Store imported ERC20 tokens on whole profile

### ISSUE THREAD

**Issue by MarkNerdi** [bloomwalletio/bloom#226]
### Task description

To prevent edgecases, it is the easiest to store erc20 on a profile level instead of accounts.

### Requirements

- [x] remove imported erc20 tokens on account
- [x] store erc20 tokens on profile
- [x] hide erc20 tokens with balance 0
