### ISSUE TITLE
️🛠 - [Task Tracker] - Add Ethereum Support

### ISSUE THREAD

**Issue by Tuditi** [bloomwalletio/bloom#2322]
### Task description

- [x] Add default EVM chains constant
- [x] Add chain configuration enums
- [x] #2345
- [x] #2359
- [x] #2382
- [x] #2381
- [x] Add network card to network drawer for each additional chain

### Requirements

Ethereum and generic EVM networks are supported in the app.

**Comment by Tuditi** [comment]
Close, since the tasks have been opened and moved to a new milestone.
