### ISSUE TITLE
️🛠 - [Task tracker]: Refactor for multi-chain support

### ISSUE THREAD

**Issue by Tuditi** [bloomwalletio/bloom#2323]
### Task description

- [x] #2338
- [x] #2374
- [x] #2335
- [x]     Network classes should updated persisted data whenever it is updated in the class
- [x] #2344
- [x]     Any Isc specific code should not be named Evm
- [x]     Add network properties to profile (e.g. evmNetwork, stardustNetwork, ...)
- [x]     chain configurations of the stardust network should only use isc types (evm networks will be in its own property of the active profile so no need for constant type checking or finding)
- [x] #2362
- [x] Replace BASE_TOKEN_CONTRACT_ADDRESS map with constant
- [x] Rename getL1Network to getStardustNetwork

### Requirements

TBD
