### ISSUE TITLE
️🛠 - Fix deep link on macOS

### ISSUE THREAD

**Issue by Tuditi** [bloomwalletio/bloom#250]
### Task description

Ensure deep links are working correctly on macOS. 

Linux changes have been addressed here: https://github.com/bloomwalletio/bloom/issues/162

### Requirements

- [ ] Logged in
- [ ] Logged out with notification to login
- [ ] App minimised (maximises app automatically and deep link after opening app)
- [ ] App closed (opens app automatically, deep link after opening app)
- [ ] App quit
