### ISSUE TITLE
️🛠 - Add Ledger confirmation flow to EVM transactions

### ISSUE THREAD

**Issue by MarkNerdi** [bloomwalletio/bloom#260]
### Task description

Currently we only have a popup to prompt the user to open ledger with the correct app. 
Similar to how we have it on stardust transactions, if the user has the correct app opened, it should show a popup with the hash of the transaction thats also displayed on the ledger device  

### Requirements

- [x] Adapt Ledger confirmation flow to also EVM transactions
- [ ] ~~Refactor Ledger transaction confirmation popup for different types of transactions~~
- [ ] ~~Move Ledger verification popup to `send-flow` directory in `views`~~
