### ISSUE TITLE
️🛠 - Refactor networkIid and chainId to be consistent

### ISSUE THREAD

**Issue by MarkNerdi** [bloomwalletio/bloom#276]
### Task description

The contactbook currently uses the network name as a unique identifier, even though it should use the networks `id`s. The underlying issue for that is that the `NetworkInput` uses `name`.

### Requirements

- [x] Design better way to store / handle the data and objects
- [x] Change `ChainId` to `EvmChainId` 
- [ ] Fix profile migration (if broken)
- [ ] Remove `NetworkId`
- [ ] Replace old usage for chains
- [ ] Replace old usage for networks
- [ ] Remove `DestinationNetwork` enum if possible 
    - This is replaced by the network ID which cleanly handles L1/L2 transactions 
- [ ] Update `DEFAULT_CHAIN_CONFIGURATIONS` with new `NetworkId`
    - Either this stays agnostic to chains or we couple it with EVM chains then we don't have to use the `NetworkId` but just the `EvmChainId`, then it becomes `DEFAULT_EVM_CHAIN_CONFIGURATIONS` 
- [ ] Change `NETWORK_ICON_SVG`
- [ ] Replace `IIscpChainMetadata` type with `IIscpChainConfiguration` in `AddIscpChainForm.svelte`
