### ISSUE TITLE
️🛠 - Polish Multichain Transak Upgrade

### ISSUE THREAD

**Issue by nicole-obrien** [bloomwalletio/bloom#2785]
### Task description

- [x] Empty placeholder when no quotes (similar to no NFTs)
- [ ] Error states if API fails
- [x] Filter out currencies that don't have payment methods
- [x] Polish the currently selected token tile to make it clear that it is clickable
- [x] Auto-select top quotation or previous quotation
- [x] Add a title to the page
- [x] Colour pills per network
- [x] Staging vs Prod API keys
- [x] IOTA vs Shimmer (Shimmer should have Ethereum Available at least)
