### ISSUE TITLE
️🛠 - Adjust CI workflows

### ISSUE THREAD

**Issue by maxwellmattryan** [bloomwalletio/bloom#301]
### Task description

The CI workflows (lint, test, ts) are run too much. The bottom line is that we need to reduce both the amount of jobs that currently being run and how many times they are being run each.

E.g.
```yaml
on:
  pull_request:
    types: [ready_for_review]
  pull_request_review:
    types: [submitted]
```

### Requirements

- [x] Make amendments above ^^^
- [x] Remove on pushes to develop (except for Snyk)
- [ ] Remove lint and format entirely (only disable workflow)
- [ ] Create wrapper CI workflow (only worth if will reduce minutes, may still allow us to see which specific job is failing)
