### ISSUE TITLE
️🛠 - Add AssetTiles to ActivityDetails

### ISSUE THREAD

**Issue by MarkNerdi** [bloomwalletio/bloom#303]
### Task description

The style of the TransactionSummary should be similarly applied to the activities. This task should only include the AssetTile on top, because we still need to define how the summary table would look like for all activity types.

As part of this PR, you should also implement the surplus as an AssetTile

### Requirements

- [ ] Add AssetTile to ActivityDetails
- [ ] Correctly calculate storage deposit
- [ ] Show surplus as AssetTile
