### ISSUE TITLE
️🛠 - Improve storage deposit / surplus on activities

### ISSUE THREAD

**Issue by MarkNerdi** [bloomwalletio/bloom#320]
### Task description

With the new improvement on SD / surplus on the send flow, we should adapt this to activities as well. Therefore we need to include the output amount into the activities and calculate the surplus from that.

### Requirements

- [ ] Add output `amount` to activities
- [ ] Correctly display storage deposit
- [ ] Correctly calculate and display surplus
