### ISSUE TITLE
️🛠 - Generate activities from balance changes

### ISSUE THREAD

**Issue by MarkNerdi** [bloomwalletio/bloom#347]
### Task description

Separate to the persisted outputs and transactions, we need to generate an activity for each balance change

### Requirements

- [x] Create `Balance changed` activity generate function
- [x] Create type for `Balance changed` activity
- [x] Implement `Balance changed` activity tile
- [x] Implement `Balance changed` activity details popup
