### ISSUE TITLE
️🛠 - Update `ActivityPopup` style

### ISSUE THREAD

**Issue by MarkNerdi** [bloomwalletio/bloom#385]
### Task description

In Figma we have new designs for the Summary Popup. 

### Requirements

- [ ] Move Pill to updated location
- [ ] Move recipient name to the title
- [ ] Move action into title
