### ISSUE TITLE
️🛠 - Validate addresses on recipient selection in send flow

### ISSUE THREAD

**Issue by nicole-obrien** [bloomwalletio/bloom#388]
### Task description

Add validation to addresses on recipient selection in send flow

### Requirements

- [x] Add validation to the EVM address on recipient selection in send flow
- [x] Add validation to the smr address on recipient selection in send flow
- [ ] ~~Move validation logic to `NetworkRecipientSelector.svelte`~~
