### ISSUE TITLE
️🛠 - Show correct amount on activity tile and details popup 

### ISSUE THREAD

**Issue by MarkNerdi** [bloomwalletio/bloom#391]
### Task description

On both the activity tile and activity details popup, the intended amount sent should be displayed, which is the `rawamount` - `sdruc` - `gas`

  

### Requirements

- [ ] show correct amount on activity tile
- [ ] show correct amount on activity details
- [ ] show correct amount on send flow

**Comment by MarkNerdi** [comment]
Fixed in https://github.com/bloomwalletio/bloom/pull/606
