### ISSUE TITLE
️🛠 - Setup WalletConnect Drawer

### ISSUE THREAD

**Issue by MarkNerdi** [bloomwalletio/bloom#395]
### Task description

We decided to implement everything around connected dapps in a drawer. In this task you should implement all related components and stores around that 

### Requirements

- [ ] Add router view
- [ ] Add empty base view
- [ ] Create router store and enums
