### ISSUE TITLE
️🛠 - Handle Ledger EVM transactions when blind signing disabled

### ISSUE THREAD

**Issue by maxwellmattryan** [bloomwalletio/bloom#432]
### Task description

We do not account for when the user has blind signing disabled **for the Ethereum app**. We need to make sure the step-by-step guide is applicable for both apps.

### Requirements

- [x] Add method of getting the app settings
- [x] Add UI/logic for when trying to sign but is disabled
- [x] Fix blind signing popup to work with either SMR/EVM
- [x] Fix logic so that request waits for user to enable blind signing or just make it work somehow
- [x] Fix closing blind signing not stopping the transfer in the background
- [x] Make L1 blind signing tx closable (investigate this flow in general)
- [x] Renaming the default poll constant to use device state instead of status
