### ISSUE TITLE
️🛠 - Implement signing method in SignMessagePopup

### ISSUE THREAD

**Issue by MarkNerdi** [bloomwalletio/bloom#513]
### Task description

Implement both `personal_sign` and `eth_sign` methods and use them in the `SignMessagePopup`.

### Requirements

- [ ] Implement `personal_sign`
- [ ] Implement `eth_sign` 
- [ ] use them in `SignMessagePopup`.
