### ISSUE TITLE
️🛠 - Add correct explorer link to L2 activities

### ISSUE THREAD

**Issue by MarkNerdi** [bloomwalletio/bloom#533]
### Task description

Currently we dont calculate the correct explorer link to the L2 activities.  Set the source network id to the activities and get the correct explorer url.

As part of this task, also replace the TransactionId button (if there is no explorer) to a copyable button

### Requirements

- [ ]  rename `networkId` to `sourceNetworkId` on activities
- [ ] Get correct explorer URL regarding `activity.sourceNetworkId`
- [ ] replace the TransactionId button (if there is no explorer) to a copyable button
