### ISSUE TITLE
️🛠 - Refactor activity generation

### ISSUE THREAD

**Issue by MarkNerdi** [bloomwalletio/bloom#605]
### Task description

- adapt the activity to the structure of the send flow. 
- cleanup amount calculations 
- dont do calculation on top of activities

### Requirements

- [ ] adapt the activity to the structure of the send flow. 
- [ ] cleanup amount calculations 
- [ ] dont do calculation on top of activities
