### ISSUE TITLE
️🛠 - Refactor and rebrand Sidebar

### ISSUE THREAD

**Issue by nicole-obrien** [bloomwalletio/bloom#675]
### Task description

Parent task for refactoring and rebranding the sidebar for Bloom

![Sidebar](https://github.com/bloomwalletio/bloom/assets/89913787/a8463566-72fb-4c6e-8883-c88fad975081)

- [x] https://github.com/bloomwalletio/bloom-ui/issues/109
- [x] #723
- [x] #756
- [x] #780
- [x] Create Stronghold Status
- [x] #704
- [x] Add icon next to Bloom logo to Bloom UI
- [x] #749
- [x] #807
- [x] #757
- [x] Polish SidebarToasts with new designs

### Requirements

- Plan component hierarchy for sidebar
- Create tasks in bloom-ui and bloom
- Develop
- Polish later
