### ISSUE TITLE
️🛠 - Refactor and rebrand top navigation and title bar

### ISSUE THREAD

**Issue by nicole-obrien** [bloomwalletio/bloom#678]
### Task description

Parent task for refactoring and rebranding the account summary for Bloom

### Requirements

- [x] Plan component hierarchy for account summary
- [x] #698
- [x] Create breadcrumb component
  - [x] Size = 13
  - [x] Consistent button style
  - [x] Logic and stores to populate breadcrumbs
- [x] Account switcher
  - [x] Consistent button style with breadcrumbs
  - [x] Text size = 13
  - [x] Simple account switcher menu
- [ ] Fix draggable areas
  - [x] Add draggable area to logged out view
  - [ ] Fix draggable area preventing close of modals due to click outside event
