### ISSUE TITLE
️🛠 - Cleanup activity list

### ISSUE THREAD

**Issue by MarkNerdi** [bloomwalletio/bloom#819]
### Task description

- [x] Dash at consolidation activities
- [x] Make searchbar not toggleable
- [x] Fix expiration time input style
