### ISSUE TITLE
️🛠 - Rebrand Contact Book

### ISSUE THREAD

**Issue by nicole-obrien** [bloomwalletio/bloom#825]
### Task description

Rebrand contact book with bloom-ui components, colors and text

### Requirements

- [x] ️🛠 - Rebrand contact list view
- [x] ️🛠 - Rebrand add contact view
- [x] ️🛠 - Rebrand contact information view
- [x] ️🛠 - Rebrand edit contact view
- [x] ️🛠 - Rebrand add network address view
- [x] ️🛠 - Rebrand edit network addresses view 
- [x] ️🛠 - Rebrand remove contact view
- [x] 🛠 - Replace text input components
- [x] 🛠 - Replace select input components
- [x] 🛠 - Rebrand contact card component
