### ISSUE TITLE
️🛠 - [Task Tracker] Rebrand Networks Drawer

### ISSUE THREAD

**Issue by nicole-obrien** [bloomwalletio/bloom#826]
### Task description

Replace components with bloom-ui, update text styles and colors

### Requirements

- [x] Overlay style
- [x] background color of drawer (awaiting confirmation)
- [x] close button
- [x] text styles on network card
- [x] qr code to use icon button
- [x] vertical table component styles
- [x] Drawer titles
- [ ] Ledger confirmation popup
