### ISSUE TITLE
️🛠 - Add feature flags for launch

### ISSUE THREAD

**Issue by Tuditi** [bloomwalletio/bloom#827]
### Task description

Add feature flags for launch and set existing ones

### Requirements

- [ ] Feature flag auto update
- [ ] Feature flag themes
- [ ] Feature flag languages
- [ ] Claim flow toggled off
- [ ] Shimmer network toggled off
- [ ] Feature flag ledger connection guide popup
