### ISSUE TITLE
️🛠 - Improve activity list

### ISSUE THREAD

**Issue by MarkNerdi** [bloomwalletio/bloom#857]
### Task description

- [x] Always show 2 addresses
- [x] `Minted` -> `Minted alias`, `Minted token`, `Minted NFT`
- [x] Update text for self transactions
- [x] Update Alias icon
- [x] Update icons on address section
