### ISSUE TITLE
️🛠 - Support mainnet ShimmerEVM

### ISSUE THREAD

**Issue by Tuditi** [bloomwalletio/bloom#860]
### Task description

Update the app, so mainnet Shimmer EVM is supported. The following things need to be updated:

- [ ] Decide if we need different colors for Shimmer EVM & Shimmer EVM Testnet
- [ ] Decide if we need different tokens
- [ ] Explorer URL
- [ ] Updated Coin Types
- [ ] Alias Address
- [ ] Remove hardcoded ShimmerEvmTestnet

### Requirements

- [ ] L1 > L2
- [ ] L2 Token transfers
- [ ] L2 > L1
