### ISSUE TITLE
️🛠 - ️Update empty gallery list

### ISSUE THREAD

**Issue by MarkNerdi** [bloomwalletio/bloom#917]
### Task description

- [x] Use branded button
- [x] Remove Firefly illustration
- [x] (add a Bloom illustration?)
